args <- commandArgs(trailingOnly=TRUE)
expr_csv <- args[1]
out_dir <- args[2]
suppressPackageStartupMessages(library(WGCNA))
options(stringsAsFactors = FALSE)
allowWGCNAThreads()
expr_df <- read.csv(expr_csv, check.names = FALSE)
traits <- expr_df[, 1:2]
datExpr <- expr_df[, -(1:2)]
rownames(datExpr) <- expr_df$gene
datExpr <- as.data.frame(t(datExpr))
trait_df <- data.frame(
  sample = rownames(datExpr),
  group = colnames(expr_df)[2]
)
sample_names <- rownames(datExpr)
group <- ifelse(grepl("control", sample_names, ignore.case=TRUE) | grepl("^CON", sample_names, ignore.case=TRUE), "Control",
         ifelse(grepl("isorhy|iroshy|IRN", sample_names, ignore.case=TRUE), "PM_Isorhy", "PM"))
traitMat <- data.frame(
  disease_status = ifelse(group == "Control", 0, 1),
  isorhy_treatment_status = ifelse(group == "PM_Isorhy", 1, 0),
  condition_code = ifelse(group == "Control", 0, ifelse(group == "PM", 1, 2))
)
rownames(traitMat) <- sample_names
sampleTree <- hclust(dist(datExpr), method = "average")
png(file.path(out_dir, "WGCNA_sample_clustering_publication.png"), width=2600, height=1800, res=600)
par(mar=c(6,4,3,2))
plot(sampleTree, main="Sample clustering", xlab="", sub="", cex.lab=1.2, cex.axis=1.0, cex.main=1.3)
dev.off()
pdf(file.path(out_dir, "WGCNA_sample_clustering_publication.pdf"), width=8.2, height=5.5)
par(mar=c(6,4,3,2))
plot(sampleTree, main="Sample clustering", xlab="", sub="", cex.lab=1.2, cex.axis=1.0, cex.main=1.3)
dev.off()
svg(file.path(out_dir, "WGCNA_sample_clustering_publication.svg"), width=8.2, height=5.5)
par(mar=c(6,4,3,2))
plot(sampleTree, main="Sample clustering", xlab="", sub="", cex.lab=1.2, cex.axis=1.0, cex.main=1.3)
dev.off()
powers = c(1:10, seq(12,20,2))
sft = pickSoftThreshold(datExpr, powerVector = powers, verbose = 0, networkType = "signed")
png(file.path(out_dir, "WGCNA_soft_threshold_publication.png"), width=3200, height=1600, res=600)
par(mfrow=c(1,2))
cex1 = 0.9
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], xlab="Soft threshold (power)", ylab="Scale free topology model fit, signed R^2", type="n", main="Scale independence")
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], labels=powers, cex=cex1, col="firebrick")
abline(h=0.80, col="grey60", lty=2)
plot(sft$fitIndices[,1], sft$fitIndices[,5], xlab="Soft threshold (power)", ylab="Mean connectivity", type="n", main="Mean connectivity")
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1, col="steelblue")
dev.off()
pdf(file.path(out_dir, "WGCNA_soft_threshold_publication.pdf"), width=10, height=4.8)
par(mfrow=c(1,2))
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], xlab="Soft threshold (power)", ylab="Scale free topology model fit, signed R^2", type="n", main="Scale independence")
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], labels=powers, cex=cex1, col="firebrick")
abline(h=0.80, col="grey60", lty=2)
plot(sft$fitIndices[,1], sft$fitIndices[,5], xlab="Soft threshold (power)", ylab="Mean connectivity", type="n", main="Mean connectivity")
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1, col="steelblue")
dev.off()
svg(file.path(out_dir, "WGCNA_soft_threshold_publication.svg"), width=10, height=4.8)
par(mfrow=c(1,2))
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], xlab="Soft threshold (power)", ylab="Scale free topology model fit, signed R^2", type="n", main="Scale independence")
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2], labels=powers, cex=cex1, col="firebrick")
abline(h=0.80, col="grey60", lty=2)
plot(sft$fitIndices[,1], sft$fitIndices[,5], xlab="Soft threshold (power)", ylab="Mean connectivity", type="n", main="Mean connectivity")
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1, col="steelblue")
dev.off()
power <- ifelse(any(!is.na(sft$fitIndices[,2]) & -sign(sft$fitIndices[,3])*sft$fitIndices[,2] > 0.8), sft$fitIndices[which.max(-sign(sft$fitIndices[,3])*sft$fitIndices[,2] > 0.8), 1], 6)
net <- blockwiseModules(datExpr, power=power, TOMType="signed", minModuleSize=20, reassignThreshold=0, mergeCutHeight=0.25, numericLabels=FALSE, pamRespectsDendro=FALSE, saveTOMs=FALSE, verbose=0)
moduleColors <- labels2colors(net$colors)
MEs <- orderMEs(net$MEs)
moduleTraitCor <- cor(MEs, traitMat, use = "p")
moduleTraitPvalue <- corPvalueStudent(moduleTraitCor, nrow(datExpr))
png(file.path(out_dir, "WGCNA_gene_dendrogram_module_colors_publication.png"), width=3200, height=1800, res=600)
plotDendroAndColors(net$dendrograms[[1]], moduleColors[net$blockGenes[[1]]], "Module colors", dendroLabels=FALSE, hang=0.03, addGuide=TRUE, guideHang=0.05, main="Gene dendrogram and module colors")
dev.off()
pdf(file.path(out_dir, "WGCNA_gene_dendrogram_module_colors_publication.pdf"), width=10, height=5.6)
plotDendroAndColors(net$dendrograms[[1]], moduleColors[net$blockGenes[[1]]], "Module colors", dendroLabels=FALSE, hang=0.03, addGuide=TRUE, guideHang=0.05, main="Gene dendrogram and module colors")
dev.off()
svg(file.path(out_dir, "WGCNA_gene_dendrogram_module_colors_publication.svg"), width=10, height=5.6)
plotDendroAndColors(net$dendrograms[[1]], moduleColors[net$blockGenes[[1]]], "Module colors", dendroLabels=FALSE, hang=0.03, addGuide=TRUE, guideHang=0.05, main="Gene dendrogram and module colors")
dev.off()
textMatrix <- paste(signif(moduleTraitCor, 2), "\n(", signif(moduleTraitPvalue, 1), ")", sep="")
png(file.path(out_dir, "WGCNA_module_trait_heatmap_publication.png"), width=2600, height=2200, res=600)
labeledHeatmap(Matrix = moduleTraitCor, xLabels = names(traitMat), yLabels = names(MEs), ySymbols = names(MEs), colorLabels = FALSE, colors = blueWhiteRed(50), textMatrix = textMatrix, setStdMargins = FALSE, cex.text = 0.8, zlim = c(-1,1), main = "Module-trait relationships")
dev.off()
pdf(file.path(out_dir, "WGCNA_module_trait_heatmap_publication.pdf"), width=8.5, height=7.2)
labeledHeatmap(Matrix = moduleTraitCor, xLabels = names(traitMat), yLabels = names(MEs), ySymbols = names(MEs), colorLabels = FALSE, colors = blueWhiteRed(50), textMatrix = textMatrix, setStdMargins = FALSE, cex.text = 0.8, zlim = c(-1,1), main = "Module-trait relationships")
dev.off()
svg(file.path(out_dir, "WGCNA_module_trait_heatmap_publication.svg"), width=8.5, height=7.2)
labeledHeatmap(Matrix = moduleTraitCor, xLabels = names(traitMat), yLabels = names(MEs), ySymbols = names(MEs), colorLabels = FALSE, colors = blueWhiteRed(50), textMatrix = textMatrix, setStdMargins = FALSE, cex.text = 0.8, zlim = c(-1,1), main = "Module-trait relationships")
dev.off()
write.csv(data.frame(module=rownames(moduleTraitCor), moduleTraitCor, check.names=FALSE), file.path(out_dir, "WGCNA_module_trait_correlation_R.csv"), row.names=FALSE)
write.csv(data.frame(gene=colnames(datExpr), module_color=moduleColors), file.path(out_dir, "WGCNA_module_assignment_R.csv"), row.names=FALSE)
